--liquibase formatted sql
--changeset cosmic:runtime-hardening-settings
INSERT INTO setting_catalog
(setting_key,display_name,category,description,value_type,default_value,origin_type,source_file,source_symbol,implementation_files,apply_mode,compatibility,compatibility_note,scope_type,risk_level,min_value,max_value,sort_order)
VALUES
('server.database.maxPoolSize','Maximum database pool size','Runtime & Performance','Maximum concurrent game-server database connections. Size against measured MySQL capacity.','INTEGER','16','YAML_EXISTING','config.yaml','server.DB_MAX_POOL_SIZE','src/main/java/config/ServerConfig.java; src/main/java/tools/DatabaseConnection.java','RESTART','SERVER_ONLY',NULL,'GLOBAL','HIGH',2,256,800),
('server.database.connectionTimeoutMs','Database connection timeout','Runtime & Performance','Maximum wait for a pooled database connection before the operation fails.','INTEGER','10000','YAML_EXISTING','config.yaml','server.DB_CONNECTION_TIMEOUT_MS','src/main/java/config/ServerConfig.java; src/main/java/tools/DatabaseConnection.java','RESTART','SERVER_ONLY',NULL,'GLOBAL','HIGH',250,120000,810),
('server.runtime.nettyBossThreads','Netty acceptor threads','Runtime & Performance','Shared threads that accept login and channel connections.','INTEGER','2','YAML_EXISTING','config.yaml','server.NETTY_BOSS_THREADS','src/main/java/net/netty/NettyServerRuntime.java','RESTART','SERVER_ONLY',NULL,'GLOBAL','MEDIUM',1,32,820),
('server.runtime.nettyWorkerThreads','Netty network worker threads','Runtime & Performance','Shared event-loop threads that process socket I/O across login and channel listeners.','INTEGER','16','YAML_EXISTING','config.yaml','server.NETTY_WORKER_THREADS','src/main/java/net/netty/NettyServerRuntime.java','RESTART','SERVER_ONLY',NULL,'GLOBAL','HIGH',1,256,830),
('server.runtime.backgroundThreads','Background worker threads','Runtime & Performance','Bounded workers for scripts and asynchronous background work.','INTEGER','8','YAML_EXISTING','config.yaml','server.BACKGROUND_THREADS','src/main/java/server/runtime/ServerExecutors.java','RESTART','SERVER_ONLY',NULL,'GLOBAL','HIGH',1,128,840),
('server.runtime.backgroundQueueCapacity','Background queue capacity','Runtime & Performance','Maximum queued background jobs before caller backpressure is applied.','INTEGER','2000','YAML_EXISTING','config.yaml','server.BACKGROUND_QUEUE_CAPACITY','src/main/java/server/runtime/ServerExecutors.java','RESTART','SERVER_ONLY',NULL,'GLOBAL','HIGH',1,100000,850),
('server.runtime.persistenceThreads','Persistence worker threads','Runtime & Performance','Dedicated workers for queued character persistence. Keep below the database pool size.','INTEGER','4','YAML_EXISTING','config.yaml','server.PERSISTENCE_THREADS','src/main/java/server/runtime/ServerExecutors.java','RESTART','SERVER_ONLY',NULL,'GLOBAL','HIGH',1,64,860),
('server.runtime.persistenceQueueCapacity','Persistence queue capacity','Runtime & Performance','Maximum queued persistence jobs before caller backpressure is applied.','INTEGER','4000','YAML_EXISTING','config.yaml','server.PERSISTENCE_QUEUE_CAPACITY','src/main/java/server/runtime/ServerExecutors.java','RESTART','SERVER_ONLY',NULL,'GLOBAL','HIGH',1,100000,870),
('server.runtime.gameplaySchedulerThreads','Gameplay scheduler threads','Runtime & Performance','Workers reserved for gameplay timers, map processing, buffs, and respawns.','INTEGER','8','YAML_EXISTING','config.yaml','server.GAMEPLAY_SCHEDULER_THREADS','src/main/java/server/runtime/ServerExecutors.java; src/main/java/server/TimerManager.java','RESTART','SERVER_ONLY',NULL,'GLOBAL','HIGH',1,128,880),
('server.runtime.maintenanceSchedulerThreads','Maintenance scheduler threads','Runtime & Performance','Workers reserved for rankings, cleanup, autosave submission, and health reporting.','INTEGER','4','YAML_EXISTING','config.yaml','server.MAINTENANCE_SCHEDULER_THREADS','src/main/java/server/runtime/ServerExecutors.java; src/main/java/server/TimerManager.java','RESTART','SERVER_ONLY',NULL,'GLOBAL','HIGH',1,64,890),
('server.runtime.slowPacketWarningMs','Slow packet warning threshold','Diagnostics','Log packet handlers whose execution reaches this duration.','LONG','100','YAML_EXISTING','config.yaml','server.SLOW_PACKET_WARNING_MS','src/main/java/client/Client.java; src/main/java/server/runtime/RuntimeMetrics.java','RESTART','SERVER_ONLY',NULL,'GLOBAL','LOW',1,60000,900),
('server.runtime.slowTaskWarningMs','Slow scheduled-task threshold','Diagnostics','Log scheduled tasks whose execution reaches this duration.','LONG','250','YAML_EXISTING','config.yaml','server.SLOW_TASK_WARNING_MS','src/main/java/server/TimerManager.java; src/main/java/server/runtime/RuntimeMetrics.java','RESTART','SERVER_ONLY',NULL,'GLOBAL','LOW',1,600000,910),
('server.runtime.healthLogIntervalMs','Runtime health log interval','Diagnostics','Interval between queue, packet, rejection, and persistence health snapshots.','LONG','60000','YAML_EXISTING','config.yaml','server.RUNTIME_HEALTH_LOG_INTERVAL_MS','src/main/java/net/server/Server.java; src/main/java/server/runtime/RuntimeMetrics.java','RESTART','SERVER_ONLY',NULL,'GLOBAL','LOW',10000,3600000,920),
('server.persistence.autosaveBatchIntervalMs','Autosave batch interval','Schedulers','Delay between staggered world autosave batches.','LONG','30000','YAML_EXISTING','config.yaml','server.AUTOSAVE_BATCH_INTERVAL_MS','src/main/java/net/server/world/World.java; src/main/java/net/server/task/CharacterAutosaverTask.java','RESTART','SERVER_ONLY',NULL,'GLOBAL','HIGH',1000,3600000,930),
('server.persistence.autosaveBatchSize','Autosave batch size','Schedulers','Maximum online characters submitted by each world autosave cycle.','INTEGER','25','YAML_EXISTING','config.yaml','server.AUTOSAVE_BATCH_SIZE','src/main/java/net/server/task/CharacterAutosaverTask.java','RESTART','SERVER_ONLY',NULL,'GLOBAL','HIGH',1,1000,940),
('server.persistence.autosaveCharacterIntervalMs','Per-character autosave interval','Schedulers','Minimum time between periodic save submissions for the same online character.','LONG','3600000','YAML_EXISTING','config.yaml','server.AUTOSAVE_CHARACTER_INTERVAL_MS','src/main/java/net/server/task/CharacterAutosaverTask.java','RESTART','SERVER_ONLY',NULL,'GLOBAL','HIGH',60000,86400000,950),
('server.persistence.dirtyAutosave','Dirty-state autosave','Schedulers','Skip periodic saves when the character persistence revision has not changed. Keep disabled until all server-originated mutations are covered.','BOOLEAN','false','YAML_EXISTING','config.yaml','server.USE_DIRTY_AUTOSAVE','src/main/java/client/Character.java; src/main/java/client/Client.java','RESTART','SERVER_ONLY','Experimental safety switch. The full staggered-save fallback remains the production default.','GLOBAL','HIGH',NULL,NULL,960);
