--liquibase formatted sql
--changeset cosmic:movement-diagnostics-settings
INSERT INTO setting_catalog
(setting_key,display_name,category,description,value_type,default_value,origin_type,source_file,source_symbol,implementation_files,apply_mode,compatibility,compatibility_note,scope_type,risk_level,min_value,max_value,sort_order)
VALUES
('server.runtime.movementDiagnostics','Movement diagnostics','Diagnostics','Enable focused logging for movement packet gaps, movement handler latency, and map visibility refresh latency. Keep disabled outside investigation windows.','BOOLEAN','false','YAML_EXISTING','config.yaml','server.MOVEMENT_DIAGNOSTICS','src/main/java/net/server/channel/handlers/MovePlayerHandler.java; src/main/java/server/maps/MapleMap.java; src/main/java/server/runtime/RuntimeMetrics.java','RESTART','SERVER_ONLY',NULL,'GLOBAL','LOW',NULL,NULL,921),
('server.runtime.movementGapWarningMs','Movement packet gap warning','Diagnostics','Warn when consecutive movement packets from the same client arrive this many milliseconds apart. Useful for client/network snap-forward investigation.','LONG','250','YAML_EXISTING','config.yaml','server.MOVEMENT_GAP_WARNING_MS','src/main/java/net/server/channel/handlers/MovePlayerHandler.java; src/main/java/server/runtime/RuntimeMetrics.java','RESTART','SERVER_ONLY',NULL,'GLOBAL','LOW',1,60000,922),
('server.runtime.movementHandlerWarningMs','Movement handler warning','Diagnostics','Warn when a movement packet handler reaches this duration.','LONG','10','YAML_EXISTING','config.yaml','server.MOVEMENT_HANDLER_WARNING_MS','src/main/java/net/server/channel/handlers/MovePlayerHandler.java; src/main/java/server/runtime/RuntimeMetrics.java','RESTART','SERVER_ONLY',NULL,'GLOBAL','LOW',1,60000,923),
('server.runtime.movementVisibilityWarningMs','Movement visibility warning','Diagnostics','Warn when map-object visibility refresh during movement reaches this duration.','LONG','10','YAML_EXISTING','config.yaml','server.MOVEMENT_VISIBILITY_WARNING_MS','src/main/java/server/maps/MapleMap.java; src/main/java/server/runtime/RuntimeMetrics.java','RESTART','SERVER_ONLY',NULL,'GLOBAL','LOW',1,60000,924);
