"use client";
import {Activity,Coins,Network,RadioTower,UsersRound} from "lucide-react";
import {useEffect,useState} from "react";
import {CmsAuth,CmsConnectionError} from "../components/auth/CmsAuth";
import {CmsNavItem,CmsShell} from "../components/layout/CmsShell";
import {PageToolbar} from "../components/ui/PageToolbar";
import {api} from "../lib/api";

type View="agents"|"runtime"|"social"|"economy";
const nav:readonly CmsNavItem<View>[]=[
 {key:"agents",label:"Agents",icon:Network},
 {key:"runtime",label:"Runtime",icon:RadioTower},
 {key:"social",label:"Social",icon:UsersRound},
 {key:"economy",label:"Economy",icon:Coins}
];
const behaviorPresets=["default","GRINDER","LOOTER","COMPANION","TOWN_IDLER","ROAMER"];

export default function App(){
 const [auth,setAuth]=useState<boolean|null>(null),[setup,setSetup]=useState(false),[startupError,setStartupError]=useState("");
 const [view,setView]=useState<View>("agents");
 useEffect(()=>{api("/api/auth/me").then(()=>setAuth(true)).catch(async()=>{
  try{const status=await api<{required:boolean}>("/api/setup/status");setSetup(status.required);setAuth(false)}
  catch{setStartupError("The Agent CMS API is offline or its database credentials are not configured.");setAuth(false)}
 })},[]);
 if(auth===null)return <div className="splash">Preparing Cosmic Agent CMS...</div>;
 if(startupError)return <CmsConnectionError mark="AC" productName="Agent CMS" message={startupError}/>;
 if(!auth)return <CmsAuth mark="AC" productName="Agent CMS" secureLabel="AGENT OPERATIONS" setup={setup} onReady={()=>setAuth(true)}/>;
 return <CmsShell activeView={view} brandMark="AC" brandSubtitle="Agent CMS" eyebrow="COSMIC AGENT CENTER"
  headerStatus="Agent operations only" inspectorOpen={false} navigation={nav}
  sidebarStatus={<><Activity size={14}/>Agent runtime console</>}
  onNavigate={setView}>{view==="agents"?<Agents/>:view==="runtime"?<Runtime/>:view==="social"?<Social/>:<Economy/>}</CmsShell>
}

function Title({title,sub}:{title:string;sub?:string}){return <div className="title"><p className="eyebrow">COSMIC AGENT CENTER</p><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>}
function Tile({label,value}:{label:string;value:any}){return <div><small>{label}</small><strong>{String(value??"unset")}</strong></div>}
function parseJson(value:any){try{return value?JSON.parse(String(value)):null}catch{return null}}
function ProposedAction({route}:{route:any}){const action=route?.proposedAction||route?.route?.proposedAction;if(!action)return null;const detail=action.portalName?`Portal ${action.portalName} on map ${action.fromMapId} -> ${action.toMapId}`:action.targetName?`Target ${action.targetName} | dx ${action.delta?.x??0}, dy ${action.delta?.y??0}`:action.target?`Target ${action.target}`:action.mapId?`Map ${action.mapId}`:"No target detail recorded";return <article className="route-next proposed-action"><strong>Proposed runtime action</strong><span>{action.type||"UNKNOWN"} | executable {String(action.executable)}</span><small>{action.reason||"No reason recorded"}</small><small>{detail}</small></article>}
function MovementResult({route}:{route:any}){const movement=route?.movementState?route:route?.movement?.movementState?route.movement:route?.route?.movementState?route.route:null;if(!movement)return null;const from=movement.from||{},to=movement.to||{},target=movement.target||{};return <article className="route-next"><strong>Movement result</strong><span>{movement.action||"MOVE"} | {movement.movementState}</span><small>from ({from.x??0},{from.y??0}) -&gt; ({to.x??0},{to.y??0}) toward ({target.x??0},{target.y??0})</small><small>target {movement.targetLabel||"unknown"} | grounded {String(Boolean(movement.grounded))} | progressed {String(Boolean(movement.progressed))} | distance {movement.distanceSqBefore??"n/a"} -&gt; {movement.distanceSqAfter??"n/a"}</small></article>}
function TargetCard({label,target}:{label:string;target:any}){if(!target)return <article className="route-next"><strong>{label}</strong><span>No visible target</span><small>Run a tick on a map with this object type to populate targeting diagnostics.</small></article>;const name=target.name||target.templateId||target.objectId;return <article className="route-next"><strong>{label}</strong><span>{name} | {target.type}</span><small>object {target.objectId} | template {target.templateId??"none"} | x {target.x}, y {target.y} | distanceSq {target.distanceSq}</small>{target.hp!=null&&<small>HP {target.hp}/{target.maxHp??"?"} | Lv. {target.level??"?"} | alive {String(target.alive)}</small>}{target.quantity!=null&&<small>Quantity {target.quantity}</small>}{target.meso!=null&&<small>Meso {target.meso}</small>}</article>}
function CombatPreview({preview}:{preview:any}){if(!preview)return null;const combat=preview.combat||{},target=combat.target||{},movement=combat.movement;return <div className="route-panel"><div className="value-grid"><Tile label="State" value={combat.combatState||"unknown"}/><Tile label="Intent" value={preview.intent}/><Tile label="Dispatch" value={preview.dispatchStatus}/><Tile label="Map" value={combat.mapId}/><Tile label="RangeSq" value={combat.attackRangeSq}/><Tile label="Target" value={target.name||target.monsterId||"none"}/></div><p className="muted">{preview.dispatchMessage}</p>{target&&<article className="route-next"><strong>Selected monster</strong><span>{target.name||target.monsterId} | object {target.objectId}</span><small>x {target.position?.x??0}, y {target.position?.y??0} | distanceSq {target.distanceSq}</small><small>HP {target.hp??"?"}/{target.maxHp??"?"} | Lv. {target.level??"?"} | alive {String(target.alive)}</small></article>}{movement&&<MovementResult route={movement}/>}<details><summary>Raw combat JSON</summary><pre>{JSON.stringify(preview,null,2)}</pre></details></div>}
function NpcPreview({preview}:{preview:any}){if(!preview)return null;const npcState=preview.npc||{},target=npcState.target||{},movement=npcState.movement;return <div className="route-panel"><div className="value-grid"><Tile label="State" value={npcState.npcState||"unknown"}/><Tile label="Intent" value={preview.intent}/><Tile label="Dispatch" value={preview.dispatchStatus}/><Tile label="Map" value={npcState.mapId}/><Tile label="RangeSq" value={npcState.interactionRangeSq}/><Tile label="Target" value={target.name||target.npcId||"none"}/></div><p className="muted">{preview.dispatchMessage}</p>{target&&<article className="route-next"><strong>Selected NPC</strong><span>{target.name||target.npcId} | object {target.objectId}</span><small>NPC ID {target.npcId??"unknown"} | x {target.position?.x??0}, y {target.position?.y??0} | distanceSq {target.distanceSq}</small><small>{npcState.npcState==="NPC_READY"?"Ready for future dialog execution.":"Approach only; dialog scripts are intentionally not opened yet."}</small></article>}{movement&&<MovementResult route={movement}/>}<details><summary>Raw NPC JSON</summary><pre>{JSON.stringify(preview,null,2)}</pre></details></div>}
function ShopPreview({preview}:{preview:any}){if(!preview)return null;const shopState=preview.shop||{},target=shopState.target||{},shop=shopState.shop||{},movement=shopState.movement;return <div className="route-panel"><div className="value-grid"><Tile label="State" value={shopState.shopState||"unknown"}/><Tile label="Intent" value={preview.intent}/><Tile label="Dispatch" value={preview.dispatchStatus}/><Tile label="Map" value={shopState.mapId}/><Tile label="Shop" value={shop.shopId||"none"}/><Tile label="Target" value={target.name||target.npcId||"none"}/></div><p className="muted">{preview.dispatchMessage}</p>{target&&<article className="route-next"><strong>Selected shop NPC</strong><span>{target.name||target.npcId} | shop {shop.shopId??"unknown"}</span><small>NPC ID {target.npcId??shop.npcId??"unknown"} | object {target.objectId} | x {target.position?.x??0}, y {target.position?.y??0} | distanceSq {target.distanceSq}</small><small>{shopState.shopState==="SHOP_READY"?"Ready for future shop open/buy/sell work.":"Approach only; shops are intentionally not opened yet."}</small></article>}{movement&&<MovementResult route={movement}/>}<details><summary>Raw shop JSON</summary><pre>{JSON.stringify(preview,null,2)}</pre></details></div>}
function InventoryPreview({preview}:{preview:any}){if(!preview)return null;const inventory=preview.inventory||{},item=inventory.matchedItem;return <div className="route-panel"><div className="value-grid"><Tile label="State" value={inventory.inventoryState||"unknown"}/><Tile label="Intent" value={preview.intent}/><Tile label="Dispatch" value={preview.dispatchStatus}/><Tile label="Map" value={inventory.mapId}/><Tile label="Inventory" value={inventory.inventoryType||"none"}/><Tile label="Mutation" value={inventory.mutationEnabled?"enabled":"read-only"}/></div><p className="muted">{preview.dispatchMessage}</p>{item?<article className="route-next"><strong>Matched inventory item</strong><span>{item.name||item.itemId} | item {item.itemId}</span><small>{item.inventoryType} slot {item.position} | quantity {item.quantity} | flag {item.flag} | expiration {item.expiration}</small><small>{inventory.note||"Readiness only; item use/equip is intentionally not executed yet."}</small></article>:<article className="route-next"><strong>No matching item</strong><span>{inventory.inventoryType||"Inventory"} did not contain the requested item.</span><small>Argument: {preview.argument||"none"} | {inventory.note||"No candidate found"}</small></article>}<details><summary>Raw inventory JSON</summary><pre>{JSON.stringify(preview,null,2)}</pre></details></div>}
function SkillPreview({preview}:{preview:any}){if(!preview)return null;const skillState=preview.skill||{},skill=skillState.selectedSkill,effect=skill?.effect;return <div className="route-panel"><div className="value-grid"><Tile label="State" value={skillState.skillState||"unknown"}/><Tile label="Intent" value={preview.intent}/><Tile label="Dispatch" value={preview.dispatchStatus}/><Tile label="Map" value={skillState.mapId}/><Tile label="Skill" value={skill?.skillId||"none"}/><Tile label="Mutation" value={skillState.mutationEnabled?"enabled":"read-only"}/></div><p className="muted">{preview.dispatchMessage}</p>{skill?<article className="route-next"><strong>Selected learned skill</strong><span>Skill {skill.skillId} | Lv. {skill.level}/{skill.masterLevel} | job {skill.skillJob}</span><small>action {String(skill.action)} | beginner {String(skill.beginnerSkill)} | fourth job {String(skill.fourthJobSkill)} | animation {skill.animationTime} ms</small>{effect&&<small>MP {effect.mpCon} | cooldown {effect.cooldown}s | damage {effect.damage} | attacks {effect.attackCount} | mobs {effect.mobCount} | statups {effect.statupCount}</small>}<small>{skillState.note||"Readiness only; skill casting is intentionally not executed yet."}</small></article>:<article className="route-next"><strong>No matching skill</strong><span>The agent has no learned skill for this request.</span><small>Argument: {preview.argument||"none"} | {skillState.note||"No candidate found"}</small></article>}<details><summary>Raw skill JSON</summary><pre>{JSON.stringify(preview,null,2)}</pre></details></div>}
function PartyPreview({preview}:{preview:any}){if(!preview)return null;const partyState=preview.party||{},party=partyState.party||{},target=partyState.target;return <div className="route-panel"><div className="value-grid"><Tile label="State" value={partyState.partyState||"unknown"}/><Tile label="Intent" value={preview.intent}/><Tile label="Dispatch" value={preview.dispatchStatus}/><Tile label="Map" value={partyState.mapId}/><Tile label="Party" value={party.partyId||"none"}/><Tile label="Mutation" value={partyState.mutationEnabled?"enabled":"read-only"}/></div><p className="muted">{preview.dispatchMessage}</p>{target?<article className="route-next"><strong>Visible party target</strong><span>{target.name||target.characterId} | character {target.characterId??"unknown"}</span><small>x {target.position?.x??0}, y {target.position?.y??0} | distanceSq {target.distanceSq} | Lv. {target.level??"?"}</small><small>{partyState.note||"Readiness only; party actions are intentionally not executed yet."}</small></article>:<article className="route-next"><strong>Party status</strong><span>{party.partyId?`Party ${party.partyId}`:"No current party or visible target"}</span><small>Members {party.memberCount??0}/6 | leader {String(Boolean(party.leader))}</small></article>}{Array.isArray(party.members)&&party.members.length?<div className="policy-grid">{party.members.map((member:any)=><article className="route-next" key={member.characterId}><strong>{member.name}</strong><span>Lv. {member.level} | Job {member.jobId}</span><small>World {member.world} | Ch. {member.channel} | Map {member.mapId} | online {String(member.online)}</small></article>)}</div>:null}<details><summary>Raw party JSON</summary><pre>{JSON.stringify(preview,null,2)}</pre></details></div>}

function Agents(){
 const [agents,setAgents]=useState<any[]>([]),[selected,setSelected]=useState<any|null>(null),[q,setQ]=useState(""),[charQ,setCharQ]=useState(""),[chars,setChars]=useState<any[]>([]),[plan,setPlan]=useState<any|null>(null),[runtimeStatus,setRuntimeStatus]=useState<any|null>(null),[logs,setLogs]=useState<any[]>([]),[memory,setMemory]=useState<any[]>([]),[goals,setGoals]=useState<any[]>([]),[policies,setPolicies]=useState<any[]>([]),[cooldowns,setCooldowns]=useState<any[]>([]),[scripts,setScripts]=useState<any[]>([]),[editingScript,setEditingScript]=useState<any|null>(null),[scriptPreview,setScriptPreview]=useState<any|null>(null),[runtimeResult,setRuntimeResult]=useState<any|null>(null),[goalDraft,setGoalDraft]=useState({goalType:"IDLE",priority:0,targetMap:"",targetRef:""}),[scriptDraft,setScriptDraft]=useState({name:"idle-town",version:1,enabled:true,scriptType:"TEXT",body:"IDLE 30"}),[reason,setReason]=useState("Updated through Agent CMS"),[error,setError]=useState("");
 const load=()=>api<any[]>(`/api/agents?q=${encodeURIComponent(q)}`).then(rows=>{setAgents(rows);if(selected){const next=rows.find(row=>row.id===selected.id);if(next)setSelected(next)}}).catch(x=>setError((x as Error).message));
 const loadScripts=()=>api<any[]>("/api/agents/scripts").then(setScripts).catch(()=>setScripts([]));
 const loadAgentDetails=()=>{if(!selected){setPlan(null);setRuntimeStatus(null);setLogs([]);setMemory([]);setGoals([]);setPolicies([]);setCooldowns([]);return}api(`/api/agents/${selected.id}/spawn-plan`).then(setPlan).catch(()=>setPlan(null));api(`/api/agents/${selected.id}/runtime/status`).then(setRuntimeStatus).catch(()=>setRuntimeStatus(null));api<any[]>(`/api/agents/${selected.id}/logs`).then(setLogs).catch(()=>setLogs([]));api<any[]>(`/api/agents/${selected.id}/memory`).then(setMemory).catch(()=>setMemory([]));api<any[]>(`/api/agents/${selected.id}/goals`).then(setGoals).catch(()=>setGoals([]));api<any[]>(`/api/agents/${selected.id}/policies`).then(setPolicies).catch(()=>setPolicies([]));api<any[]>(`/api/agents/${selected.id}/cooldowns`).then(setCooldowns).catch(()=>setCooldowns([]))};
 useEffect(()=>{const timer=setTimeout(load,160);return()=>clearTimeout(timer)},[q]);
 useEffect(()=>{loadScripts()},[]);
 useEffect(()=>{setRuntimeResult(null);loadAgentDetails()},[selected?.id]);
 useEffect(()=>{const timer=setTimeout(()=>{if(charQ.trim().length<2){setChars([]);return}api<any[]>(`/api/agents/characters?q=${encodeURIComponent(charQ)}`).then(setChars).catch(()=>setChars([]))},160);return()=>clearTimeout(timer)},[charQ]);
 async function createAgent(characterId:number){setError("");try{const created=await api<any>("/api/agents",{method:"POST",body:JSON.stringify({characterId,enabled:false,defaultMode:"IDLE",behaviorProfile:"default",personalityProfile:"default",llmEnabled:false})});setSelected(created);setCharQ("");setChars([]);load()}catch(x){setError((x as Error).message)}}
 async function saveAgent(){if(!selected)return;setError("");try{const updated=await api<any>(`/api/agents/${selected.id}`,{method:"PUT",body:JSON.stringify({enabled:Boolean(selected.enabled),displayName:selected.display_name,defaultMode:selected.default_mode,behaviorProfile:selected.behavior_profile,personalityProfile:selected.personality_profile,scriptName:selected.script_name,llmEnabled:Boolean(selected.llm_enabled),reason})});setSelected(updated);load()}catch(x){setError((x as Error).message)}}
 async function runtimeAction(action:string){if(!selected)return;setError("");try{const result=await api<any>(`/api/agents/${selected.id}/runtime/${action}`,{method:"POST"});setRuntimeResult(result);load();loadAgentDetails()}catch(x){setError((x as Error).message)}}
 async function setPolicy(policy:any,enabled:boolean){if(!selected)return;setError("");try{await api<any>(`/api/agents/${selected.id}/policies/${encodeURIComponent(policy.key)}`,{method:"PUT",body:JSON.stringify({enabled,reason})});loadAgentDetails()}catch(x){setError((x as Error).message)}}
 async function resetPolicy(policy:any){if(!selected)return;setError("");try{await api<any>(`/api/agents/${selected.id}/policies/${encodeURIComponent(policy.key)}?reason=${encodeURIComponent(reason)}`,{method:"DELETE"});loadAgentDetails()}catch(x){setError((x as Error).message)}}
 async function setCooldown(cooldown:any,millis:any){if(!selected)return;setError("");const parsed=Number(millis);if(!Number.isFinite(parsed)||parsed<0){setError("Cooldown must be a non-negative number of milliseconds.");return}try{await api<any>(`/api/agents/${selected.id}/cooldowns/${encodeURIComponent(cooldown.key)}`,{method:"PUT",body:JSON.stringify({millis:Math.round(parsed),reason})});loadAgentDetails()}catch(x){setError((x as Error).message)}}
 async function resetCooldown(cooldown:any){if(!selected)return;setError("");try{await api<any>(`/api/agents/${selected.id}/cooldowns/${encodeURIComponent(cooldown.key)}?reason=${encodeURIComponent(reason)}`,{method:"DELETE"});loadAgentDetails()}catch(x){setError((x as Error).message)}}
 async function createGoal(){if(!selected)return;setError("");try{await api<any>(`/api/agents/${selected.id}/goals`,{method:"POST",body:JSON.stringify({goalType:goalDraft.goalType,priority:Number(goalDraft.priority)||0,status:"PENDING",targetMap:goalDraft.targetMap?Number(goalDraft.targetMap):null,targetRef:goalDraft.targetRef||null})});setGoalDraft({...goalDraft,targetMap:"",targetRef:""});loadAgentDetails()}catch(x){setError((x as Error).message)}}
 async function setGoalStatus(goal:any,status:string){if(!selected)return;setError("");try{await api<any>(`/api/agents/${selected.id}/goals/${goal.id}/status`,{method:"PUT",body:JSON.stringify({status,reason})});loadAgentDetails()}catch(x){setError((x as Error).message)}}
 async function saveScript(script:any){setError("");try{const saved=await api<any>(script.id?`/api/agents/scripts/${script.id}`:"/api/agents/scripts",{method:script.id?"PUT":"POST",body:JSON.stringify({name:script.name,version:Number(script.version)||1,enabled:Boolean(script.enabled),scriptType:script.script_type||script.scriptType||"TEXT",body:script.body||"",reason})});setEditingScript(null);setScriptDraft({...scriptDraft,name:"idle-town",body:"IDLE 30"});loadScripts();return saved}catch(x){setError((x as Error).message)}}
 async function previewScript(script:any){setError("");try{const preview=await api<any>("/api/agents/scripts/preview",{method:"POST",body:JSON.stringify({body:script.body||""})});setScriptPreview({...preview,name:script.name||"draft"})}catch(x){setError((x as Error).message)}}
 const parseDetails=(value:any)=>{try{return value?JSON.parse(String(value)):null}catch{return null}};
 const goalProgress=(goal:any)=>parseDetails(goal.progress_json);
 const latestRouteMemory=memory.find(item=>item.event_type==="NAVIGATION_ROUTE");
 const latestRoute=parseDetails(latestRouteMemory?.details_json);
 const route=latestRoute?.route;
 const latestTargetScanMemory=memory.find(item=>item.event_type==="TARGET_SCAN");
 const targetScan=parseDetails(latestTargetScanMemory?.details_json);
 const latestCombatMemory=memory.find(item=>item.event_type==="COMBAT_PREVIEW");
 const combatPreview=parseDetails(latestCombatMemory?.details_json);
 const latestNpcMemory=memory.find(item=>item.event_type==="NPC_PREVIEW");
 const npcPreview=parseDetails(latestNpcMemory?.details_json);
 const latestShopMemory=memory.find(item=>item.event_type==="SHOP_PREVIEW");
 const shopPreview=parseDetails(latestShopMemory?.details_json);
 const latestInventoryMemory=memory.find(item=>item.event_type==="INVENTORY_PREVIEW");
 const inventoryPreview=parseDetails(latestInventoryMemory?.details_json);
 const latestSkillMemory=memory.find(item=>item.event_type==="SKILL_PREVIEW");
 const skillPreview=parseDetails(latestSkillMemory?.details_json);
 const latestPartyMemory=memory.find(item=>item.event_type==="PARTY_PREVIEW");
 const partyPreview=parseDetails(latestPartyMemory?.details_json);
 return <><article className="panel intro"><Title title="Agent operations" sub="Profiles, goals, scripts, policies, route state, memory and runtime controls for server-side agents."/></article>
  <PageToolbar query={q} onQueryChange={setQ} placeholder="Search agent, account, character or ID"/>
  {error&&<div className="error">{error}</div>}
  <div className="agent-layout"><section className="panel"><Title title="Agent roster" sub={`${agents.length} profiles. Disabled profiles never enter the runtime registry.`}/>
   <div className="agent-list">{agents.map(agent=><button className={`agent-card ${selected?.id===agent.id?"selected":""}`} key={agent.id} onClick={()=>setSelected(agent)}>
    <div><strong>{agent.display_name||agent.character_name}</strong><small>{agent.account_name} {"->"} {agent.character_name} | Lv. {agent.level} | World {agent.world}</small></div>
    <span className={agent.enabled?"active-state":"inactive-state"}>{agent.enabled?"Enabled":"Disabled"}</span></button>)}</div></section>
   <section className="panel"><Title title="Create from character" sub="Regular Cosmic characters can be marked as future agents without changing their account."/>
    <div className="search compact"><Network size={17}/><input value={charQ} onChange={e=>setCharQ(e.target.value)} placeholder="Search account, IGN or character ID"/></div>
    <div className="agent-list compact-list">{chars.map(character=><button className="agent-card" disabled={Boolean(character.agent_profile_id)} key={character.id} onClick={()=>createAgent(character.id)}>
     <div><strong>{character.account_name} {"->"} {character.character_name}</strong><small>Lv. {character.level} | Job {character.job} | World {character.world} | Map {character.map}</small></div>
     <span className={character.agent_profile_id?"inactive-state":"active-state"}>{character.agent_profile_id?"Already agent":"Create"}</span></button>)}</div></section></div>
  {selected&&<div className="agent-detail"><section className="panel"><Title title={`${selected.display_name||selected.character_name} profile`} sub="These settings are persisted in the game database agent tables and picked up by Cosmic after restart."/>
   <div className="value-grid agent-edit"><label><small>Enabled</small><select className="edit" value={String(Boolean(selected.enabled))} onChange={e=>setSelected({...selected,enabled:e.target.value==="true"})}><option value="false">false</option><option value="true">true</option></select></label>
    <label><small>Display name</small><input className="edit" value={selected.display_name||""} onChange={e=>setSelected({...selected,display_name:e.target.value})}/></label>
    <label><small>Default mode</small><select className="edit" value={selected.default_mode||"IDLE"} onChange={e=>setSelected({...selected,default_mode:e.target.value})}><option>IDLE</option><option>ROAM</option><option>GRIND</option><option>LOOT</option><option>FOLLOW</option></select></label>
    <label><small>Behavior profile</small><select className="edit" value={selected.behavior_profile||"default"} onChange={e=>setSelected({...selected,behavior_profile:e.target.value})}>{behaviorPresets.map(preset=><option key={preset}>{preset}</option>)}</select></label>
    <label><small>Personality profile</small><input className="edit" value={selected.personality_profile||"default"} onChange={e=>setSelected({...selected,personality_profile:e.target.value})}/></label>
    <label><small>Script name</small><input className="edit" list="agent-script-names" value={selected.script_name||""} onChange={e=>setSelected({...selected,script_name:e.target.value})}/><datalist id="agent-script-names">{scripts.map(script=><option key={script.id} value={script.name}/>)}</datalist></label>
    <label><small>LLM enabled</small><select className="edit" value={String(Boolean(selected.llm_enabled))} onChange={e=>setSelected({...selected,llm_enabled:e.target.value==="true"})}><option value="false">false</option><option value="true">true</option></select></label></div>
   <textarea value={reason} onChange={e=>setReason(e.target.value)} /><div className="actions"><button className="primary" onClick={saveAgent}>Save profile</button></div></section>
   <section className="panel"><Title title="Control preflight" sub="Prepare, enter, runtime tick and release use the Cosmic bridge when enabled."/>
    {plan?<><div className="value-grid"><Tile label="Ready" value={String(plan.ready)}/><Tile label="World" value={plan.world}/><Tile label="Channel" value={plan.channel}/><Tile label="Map" value={plan.mapId}/><Tile label="Spawn point" value={plan.spawnPoint}/><Tile label="Message" value={plan.message}/></div>
     <div className="actions runtime-actions"><button className="secondary" onClick={()=>runtimeAction("prepare")}>Prepare</button><button className="secondary" onClick={()=>runtimeAction("enter")}>Enter world</button><button className="secondary" onClick={()=>runtimeAction("tick")}>Dry-run tick</button><button className="danger" onClick={()=>runtimeAction("release")}>Release</button></div>
     {runtimeResult&&<pre className="code-box">{JSON.stringify(runtimeResult,null,2)}</pre>}</>:<p className="muted">Select an agent to view preflight state.</p>}</section>
   <section className="panel"><Title title="Runtime health" sub="Latest session, action, memory, chat and economy checkpoints."/>
    {runtimeStatus?<div className="value-grid"><Tile label="Session" value={runtimeStatus.latestSession?.state||"none"}/><Tile label="Task" value={runtimeStatus.latestSession?.current_task||"none"}/><Tile label="Last tick" value={runtimeStatus.latestSession?.last_tick_at||"never"}/><Tile label="Last action" value={runtimeStatus.latestAction?.action_type||"none"}/><Tile label="Action status" value={runtimeStatus.latestAction?.status||"none"}/><Tile label="Last memory" value={runtimeStatus.latestMemory?.event_type||"none"}/><Tile label="Last chat" value={runtimeStatus.latestChat?.message||"none"}/><Tile label="Last economy" value={runtimeStatus.latestEconomy?.entry_type||"none"}/></div>:<p className="muted">No runtime status loaded.</p>}</section>
   <section className="panel full-span"><Title title="Goals" sub="Dry-run planner reads the highest priority active goal before falling back to scripts."/>
    <div className="filters compact"><select value={goalDraft.goalType} onChange={e=>setGoalDraft({...goalDraft,goalType:e.target.value})}><option>IDLE</option><option>WAIT</option><option>ROAM</option><option>MOVE_TO_MAP</option><option>FOLLOW_CHARACTER</option><option>GRIND_TO_LEVEL</option><option>LOOT</option><option>NPC</option><option>SHOP</option><option>SAY</option><option>USE_ITEM</option><option>EQUIP</option><option>SKILL</option></select><input className="edit" type="number" value={goalDraft.priority} onChange={e=>setGoalDraft({...goalDraft,priority:Number(e.target.value)})} placeholder="Priority"/><input className="edit" value={goalDraft.targetMap} onChange={e=>setGoalDraft({...goalDraft,targetMap:e.target.value})} placeholder="Target map"/><input className="edit" value={goalDraft.targetRef} onChange={e=>setGoalDraft({...goalDraft,targetRef:e.target.value})} placeholder={goalDraft.goalType==="FOLLOW_CHARACTER"?"Target IGN or character ID":"Target ref"}/><button className="primary" onClick={createGoal}>Add goal</button></div>
    {goals.length?goals.map(goal=>{const progress=goalProgress(goal);return <div className="audit-row" key={goal.id}><strong>{goal.goal_type}</strong><code>{goal.status} | priority {goal.priority}</code><span>{String(goal.updated_at)}</span><p>Target map {goal.target_map??"any"} | ref {goal.target_ref??"none"}</p>{progress&&<><p>Last tick: {progress.lastIntent}{progress.lastArgument?` ${progress.lastArgument}`:""} | dispatch {progress.dispatchStatus} | map {progress.mapId} | mobs {progress.monsters} | drops {progress.drops}</p><div className="goal-diagnosis"><span className={String(progress.diagnosisState||"RUNNING").includes("BLOCKED")||String(progress.diagnosisState||"").includes("FAILED")?"inactive-state":"active-state"}>{progress.diagnosisState||"RUNNING"}</span><div><strong>{progress.diagnosisReason||progress.goalReason||"No diagnosis recorded yet"}</strong><small>{progress.recommendedAction||"Run a runtime tick to refresh diagnostics."}</small></div></div></>}<div className="policy-actions"><button className="secondary" onClick={()=>setGoalStatus(goal,"ACTIVE")}>Activate</button><button className="secondary" onClick={()=>setGoalStatus(goal,"PAUSED")}>Pause</button><button className="secondary" onClick={()=>setGoalStatus(goal,"COMPLETED")}>Complete</button><button className="secondary" onClick={()=>setGoalStatus(goal,"FAILED")}>Fail</button><button className="danger" onClick={()=>setGoalStatus(goal,"CANCELLED")}>Cancel</button></div>{goal.progress_json&&<details><summary>Progress JSON</summary><pre>{goal.progress_json}</pre></details>}</div>}):<p className="muted">No goals yet. Without a goal the agent falls back to script/default idle planning.</p>}</section>
   <section className="panel full-span"><Title title="Navigation route state" sub="Latest route and movement state recorded by the server-side navigation adapter."/>
    {route?<div className="route-panel"><div className="value-grid"><Tile label="State" value={route.routeState||route.followState||route.movementState||"unknown"}/><Tile label="Map" value={route.fromMapId||route.mapId}/><Tile label="Target" value={route.toMapId||route.requestedTarget||route.targetLabel||"unset"}/><Tile label="Steps" value={route.stepCount??route.route?.stepCount??"n/a"}/><Tile label="Dispatch" value={latestRoute.dispatchStatus}/><Tile label="Recorded" value={latestRouteMemory?.created_at}/></div><p className="muted">{latestRoute.dispatchMessage||route.message}</p><ProposedAction route={route}/><MovementResult route={route}/>{route.locatedTarget&&<article className="route-next"><strong>Located follow target</strong><span>{route.locatedTarget.name} on world {route.locatedTarget.world}, channel {route.locatedTarget.channel}, map {route.locatedTarget.mapId}</span><small>{route.locatedTarget.online?"online":"saved location"} | x {route.locatedTarget.position?.x??0}, y {route.locatedTarget.position?.y??0}</small></article>}{route.target&&<article className="route-next"><strong>Visible follow target</strong><span>{route.target.name} on map {route.mapId}</span><small>x {route.target.position?.x??0}, y {route.target.position?.y??0} | distanceSq {route.target.distanceSq}</small></article>}{(route.nextStep||route.route?.nextStep)&&<article className="route-next"><strong>Next portal</strong><span>{(route.nextStep||route.route.nextStep).portalName} on map {(route.nextStep||route.route.nextStep).fromMapId} -&gt; {(route.nextStep||route.route.nextStep).toMapId}</span><small>x {(route.nextStep||route.route.nextStep).position?.x??0}, y {(route.nextStep||route.route.nextStep).position?.y??0} | {(route.nextStep||route.route.nextStep).open?"open":"closed"} | {(route.nextStep||route.route.nextStep).scripted?"scripted":"plain portal"}</small></article>}{Array.isArray(route.steps||route.route?.steps)&&(route.steps||route.route?.steps).length?<ol className="route-steps">{(route.steps||route.route.steps).map((step:any,index:number)=><li key={`${step.fromMapId}-${step.portalId}-${index}`}><strong>{index+1}. {step.fromMapName||step.fromMapId}</strong><span>Portal {step.portalName} -&gt; map {step.toMapId}</span><small>x {step.position?.x??0}, y {step.position?.y??0} | type {step.portalType} | {step.open?"open":"closed"} | {step.scripted?"scripted":"plain"}</small></li>)}</ol>:<p className="muted">{route.followState?"Follow target has no portal route yet.":route.movementState?"No portal route needed for this local movement.":"No route steps recorded."}</p>}<details><summary>Raw route JSON</summary><pre>{JSON.stringify(latestRoute,null,2)}</pre></details></div>:<p className="muted">No route state yet. Add or activate a MOVE_TO_MAP or FOLLOW_CHARACTER goal, allow navigation policy, enter the agent, then run a runtime tick.</p>}</section>
   <section className="panel full-span"><Title title="Target scan" sub="Nearest visible interactable objects from the last pilot tick. This is read-only groundwork for combat, NPC and companion behavior."/>
    {targetScan?<div className="route-panel"><div className="value-grid"><Tile label="Map" value={targetScan.mapId}/><Tile label="Players" value={targetScan.counts?.players}/><Tile label="Monsters" value={targetScan.counts?.monsters}/><Tile label="Drops" value={targetScan.counts?.drops}/><Tile label="NPCs" value={targetScan.counts?.npcs}/><Tile label="Recorded" value={latestTargetScanMemory?.created_at}/></div><div className="policy-grid"><TargetCard label="Nearest player" target={targetScan.nearest?.player}/><TargetCard label="Nearest monster" target={targetScan.nearest?.monster}/><TargetCard label="Nearest drop" target={targetScan.nearest?.drop}/><TargetCard label="Nearest NPC" target={targetScan.nearest?.npc}/><TargetCard label="Nearest reactor" target={targetScan.nearest?.reactor}/></div><details><summary>Raw target scan JSON</summary><pre>{JSON.stringify(targetScan,null,2)}</pre></details></div>:<p className="muted">No target scan yet. Enter an agent and run a runtime tick to capture nearby interactable objects.</p>}</section>
   <section className="panel full-span"><Title title="Combat preview" sub="Combat v1: choose a valid monster, approach range, and apply conservative non-skill basic attacks to non-boss monsters."/>
    {combatPreview?<CombatPreview preview={combatPreview}/>:<p className="muted">No combat preview yet. Add or activate an ATTACK or GRIND goal and allow combat policy to capture target selection.</p>}</section>
   <section className="panel full-span"><Title title="NPC interaction preview" sub="NPC v1: choose and approach visible NPCs, then stop at readiness. Dialog scripts are not opened yet."/>
    {npcPreview?<NpcPreview preview={npcPreview}/>:<p className="muted">No NPC preview yet. Add or activate an NPC goal and allow NPC policy to capture target selection and approach state.</p>}</section>
   <section className="panel full-span"><Title title="Shop interaction preview" sub="Shop v1: choose and approach visible shop NPCs, then stop at readiness. Buying and selling are not enabled yet."/>
    {shopPreview?<ShopPreview preview={shopPreview}/>:<p className="muted">No shop preview yet. Add or activate a SHOP goal and allow shop policy to capture shop NPC selection and approach state.</p>}</section>
   <section className="panel full-span"><Title title="Inventory preview" sub="Inventory v1: resolve USEITEM and EQUIP requests against current inventory, then stop at readiness. No item is consumed or equipped yet."/>
    {inventoryPreview?<InventoryPreview preview={inventoryPreview}/>:<p className="muted">No inventory preview yet. Add or activate a USE_ITEM or EQUIP goal and allow inventory policy to capture matching item state.</p>}</section>
   <section className="panel full-span"><Title title="Skill preview" sub="Skill v1: resolve SKILL/CAST requests against learned skills, then stop at readiness. No skill is cast yet."/>
    {skillPreview?<SkillPreview preview={skillPreview}/>:<p className="muted">No skill preview yet. Add or activate a SKILL goal and allow skill policy to capture learned skill metadata.</p>}</section>
   <section className="panel full-span"><Title title="Party preview" sub="Party v1: inspect current party and visible party targets, then stop at readiness. Invites, joins, leaves and creates are not enabled yet."/>
    {partyPreview?<PartyPreview preview={partyPreview}/>:<p className="muted">No party preview yet. Add or activate a PARTY goal and allow party policy to capture current party and visible player state.</p>}</section>
   <section className="panel full-span"><Title title="Capability policies" sub="Per-agent policy gates. Enabling a capability only passes policy; unimplemented runtime handlers still block gameplay actions."/>
    <div className="policy-grid">{policies.map(policy=><article className="policy-card" key={policy.key}><div><strong>{policy.label}</strong><code>{policy.key}</code><p>{policy.description}</p><small>Default {String(policy.defaultEnabled)} | Global {policy.globalValue??"unset"} | Agent {policy.agentValue??"unset"}</small></div><span className={policy.effective?"active-state":"inactive-state"}>{policy.effective?"Allowed":"Blocked"}</span><div className="policy-actions"><button className="secondary" onClick={()=>setPolicy(policy,true)}>Allow</button><button className="secondary" onClick={()=>setPolicy(policy,false)}>Block</button><button className="secondary" disabled={!policy.overridden} onClick={()=>resetPolicy(policy)}>Use fallback</button></div></article>)}</div></section>
   <section className="panel full-span"><Title title="Intent cooldowns" sub="Per-agent pacing limits in milliseconds. Intent overrides win over capability cooldowns; unset rows fall back to global policy or built-in defaults."/>
    <div className="policy-grid">{cooldowns.map(cooldown=><article className="policy-card" key={cooldown.key}><div><strong>{cooldown.label}</strong><code>{cooldown.key}</code><p>{cooldown.description}</p><small>Default {Number(cooldown.defaultMillis).toLocaleString()} ms | Global {cooldown.globalValue??"unset"} | Agent {cooldown.agentValue??"unset"}</small></div><span className="active-state">{Number(cooldown.effectiveMillis).toLocaleString()} ms</span><div className="policy-actions"><input className="edit" key={`${cooldown.key}-${cooldown.effectiveMillis}-${cooldown.agentValue??"fallback"}`} type="number" min="0" max="3600000" defaultValue={cooldown.effectiveMillis} onKeyDown={e=>{if(e.key==="Enter")setCooldown(cooldown,(e.target as HTMLInputElement).value)}}/><button className="secondary" onClick={e=>setCooldown(cooldown,e.currentTarget.parentElement?.querySelector("input")?.value??cooldown.effectiveMillis)}>Save ms</button><button className="secondary" disabled={!cooldown.overridden} onClick={()=>resetCooldown(cooldown)}>Use fallback</button></div></article>)}</div></section>
   <section className="panel full-span"><Title title="Script library" sub="Reusable runtime behavior scripts."/>
    <div className="filters compact"><input className="edit" value={scriptDraft.name} onChange={e=>setScriptDraft({...scriptDraft,name:e.target.value})} placeholder="Script name"/><input className="edit" type="number" value={scriptDraft.version} onChange={e=>setScriptDraft({...scriptDraft,version:Number(e.target.value)})} placeholder="Version"/><select value={String(scriptDraft.enabled)} onChange={e=>setScriptDraft({...scriptDraft,enabled:e.target.value==="true"})}><option value="true">enabled</option><option value="false">disabled</option></select><button className="secondary" onClick={()=>previewScript(scriptDraft)}>Preview</button><button className="primary" onClick={()=>saveScript(scriptDraft)}>Create script</button></div><textarea className="script-editor" value={scriptDraft.body} onChange={e=>setScriptDraft({...scriptDraft,body:e.target.value})}/>
    {scriptPreview&&<div className="script-preview"><strong>Preview: {scriptPreview.name}</strong><span className={scriptPreview.safeToSave?"active-state":"inactive-state"}>{scriptPreview.message}</span><div className="script-preview-list">{(scriptPreview.steps||[]).map((step:any,index:number)=><article key={`${scriptPreview.name}-${step.line}-${index}-${step.intent}`}><code>Line {step.line}: {step.command}{Number(step.repeatCount)>1?` (${step.repeatIndex}/${step.repeatCount})`:""}</code><strong>{step.intent}</strong><small>{step.capability} | arg {step.argument??"none"} | {Number(step.durationMillis||0).toLocaleString()} ms</small>{step.warning&&<p>{step.warning}</p>}</article>)}</div></div>}
    {scripts.length?scripts.map(script=><div className="audit-row" key={script.id}><strong>{script.name}</strong><code>v{script.version} | {script.enabled?"enabled":"disabled"} | {script.script_type}</code><span>{String(script.updated_at)}</span>{editingScript?.id===script.id?<><textarea className="script-editor" value={editingScript.body||""} onChange={e=>setEditingScript({...editingScript,body:e.target.value})}/><div className="filters compact"><input className="edit" value={editingScript.name||""} onChange={e=>setEditingScript({...editingScript,name:e.target.value})}/><input className="edit" type="number" value={editingScript.version||1} onChange={e=>setEditingScript({...editingScript,version:Number(e.target.value)})}/><button className="secondary" onClick={()=>previewScript(editingScript)}>Preview</button><button className="secondary" onClick={()=>setEditingScript(null)}>Cancel</button><button className="primary" onClick={()=>saveScript(editingScript)}>Save script</button></div></>:<><p>{String(script.body||"").split(/\r?\n/).slice(0,3).join(" | ")}</p><div className="policy-actions"><button className="secondary" onClick={()=>previewScript(script)}>Preview</button><button className="secondary" onClick={()=>setEditingScript(script)}>Edit</button><button className="secondary" onClick={()=>setSelected(selected?{...selected,script_name:script.name}:selected)}>Use on selected agent</button></div></>}</div>):<p className="muted">No reusable scripts yet.</p>}</section>
   <section className="panel full-span"><Title title="Recent memory" sub="Compact observation checkpoints recorded during runtime ticks."/>
    {memory.length?memory.map(item=><div className="audit-row" key={item.id}><strong>{item.event_type}</strong><code>Importance {item.importance}</code><span>{String(item.created_at)}</span><p>{item.summary}</p>{item.details_json&&<details><summary>Details</summary><pre>{item.details_json}</pre></details>}</div>):<p className="muted">No memory events yet. Run a runtime tick after entering an agent.</p>}</section>
   <section className="panel full-span"><Title title="Recent action logs" sub="Lifecycle and future action records from agent_action_logs"/>
    {logs.length?logs.map(log=><div className="audit-row" key={log.id}><strong>{log.action_type}</strong><code>{log.status}</code><span>{String(log.created_at)}</span><p>{log.message}</p></div>):<p className="muted">No runtime logs yet.</p>}</section></div>}</>
}

function Runtime(){
 const [q,setQ]=useState(""),[sessions,setSessions]=useState<any[]>([]),[summary,setSummary]=useState<any|null>(null),[globalPolicies,setGlobalPolicies]=useState<any[]>([]),[globalCooldowns,setGlobalCooldowns]=useState<any[]>([]),[reason,setReason]=useState("Updated global agent defaults through Agent CMS"),[error,setError]=useState("");
 const loadGlobalDefaults=()=>{api<any[]>("/api/agents/policies/global").then(setGlobalPolicies).catch(()=>setGlobalPolicies([]));api<any[]>("/api/agents/cooldowns/global").then(setGlobalCooldowns).catch(()=>setGlobalCooldowns([]))};
 useEffect(()=>{const timer=setTimeout(()=>{api<any[]>(`/api/agents/runtime/sessions?q=${encodeURIComponent(q)}`).then(setSessions).catch(x=>setError((x as Error).message));api<any>("/api/agents/runtime/summary").then(setSummary).catch(()=>setSummary(null));loadGlobalDefaults()},160);return()=>clearTimeout(timer)},[q]);
 async function setGlobalPolicy(policy:any,enabled:boolean){setError("");try{await api<any>(`/api/agents/policies/global/${encodeURIComponent(policy.key)}`,{method:"PUT",body:JSON.stringify({enabled,reason})});loadGlobalDefaults()}catch(x){setError((x as Error).message)}}
 async function resetGlobalPolicy(policy:any){setError("");try{await api<any>(`/api/agents/policies/global/${encodeURIComponent(policy.key)}?reason=${encodeURIComponent(reason)}`,{method:"DELETE"});loadGlobalDefaults()}catch(x){setError((x as Error).message)}}
 async function setGlobalCooldown(cooldown:any,millis:any){setError("");const parsed=Number(millis);if(!Number.isFinite(parsed)||parsed<0){setError("Cooldown must be a non-negative number of milliseconds.");return}try{await api<any>(`/api/agents/cooldowns/global/${encodeURIComponent(cooldown.key)}`,{method:"PUT",body:JSON.stringify({millis:Math.round(parsed),reason})});loadGlobalDefaults()}catch(x){setError((x as Error).message)}}
 async function resetGlobalCooldown(cooldown:any){setError("");try{await api<any>(`/api/agents/cooldowns/global/${encodeURIComponent(cooldown.key)}?reason=${encodeURIComponent(reason)}`,{method:"DELETE"});loadGlobalDefaults()}catch(x){setError((x as Error).message)}}
 async function stopStaleSession(session:any){setError("");try{await api<any>(`/api/agents/runtime/sessions/${session.id}/mark-stale-stopped`,{method:"POST",body:JSON.stringify({reason})});api<any[]>(`/api/agents/runtime/sessions?q=${encodeURIComponent(q)}`).then(setSessions);api<any>("/api/agents/runtime/summary").then(setSummary).catch(()=>setSummary(null))}catch(x){setError((x as Error).message)}}
 const active=sessions.filter(row=>!row.ended_at).length;
 const sessionSummary=summary?.sessions||{},actionSummary=summary?.actions24h||{},problems=summary?.latestProblems||[];
 return <><article className="panel intro"><Title title="Runtime sessions" sub="Live and historical runtime shells. This is read-only observability for agent lifecycle state."/></article>
  <div className="metrics compact-metrics"><article><RadioTower/><small>Open sessions</small><strong>{sessionSummary.open_sessions??active}</strong></article><article><Activity/><small>Stale sessions</small><strong>{sessionSummary.stale_sessions??0}</strong></article><article><Activity/><small>Blocked actions 24h</small><strong>{actionSummary.blocked_actions??0}</strong></article><article><Activity/><small>Failed actions 24h</small><strong>{actionSummary.failed_actions??0}</strong></article><article><Activity/><small>Cooldown blocks 24h</small><strong>{actionSummary.cooldown_blocks??0}</strong></article><article><Activity/><small>Loaded rows</small><strong>{sessions.length}</strong></article></div>
  <PageToolbar query={q} onQueryChange={setQ} placeholder="Search agent, character, state or task"/>
  {error&&<div className="error">{error}</div>}
  <section className="panel"><Title title="Global runtime defaults" sub="Fallback capability gates and cooldowns used by every agent unless that agent has its own override."/>
   <textarea value={reason} onChange={e=>setReason(e.target.value)} />
   <h3>Capability defaults</h3><div className="policy-grid">{globalPolicies.map(policy=><article className="policy-card" key={policy.key}><div><strong>{policy.label}</strong><code>{policy.key}</code><p>{policy.description}</p><small>Built-in default {String(policy.defaultEnabled)} | Global row {policy.globalValue??"unset"}</small></div><span className={policy.effective?"active-state":"inactive-state"}>{policy.effective?"Allowed by default":"Blocked by default"}</span><div className="policy-actions"><button className="secondary" onClick={()=>setGlobalPolicy(policy,true)}>Allow</button><button className="secondary" onClick={()=>setGlobalPolicy(policy,false)}>Block</button><button className="secondary" disabled={!policy.overridden} onClick={()=>resetGlobalPolicy(policy)}>Use built-in</button></div></article>)}</div>
   <h3>Cooldown defaults</h3><div className="policy-grid">{globalCooldowns.map(cooldown=><article className="policy-card" key={cooldown.key}><div><strong>{cooldown.label}</strong><code>{cooldown.key}</code><p>{cooldown.description}</p><small>Built-in default {Number(cooldown.defaultMillis).toLocaleString()} ms | Global row {cooldown.globalValue??"unset"}</small></div><span className="active-state">{Number(cooldown.effectiveMillis).toLocaleString()} ms</span><div className="policy-actions"><input className="edit" key={`${cooldown.key}-${cooldown.effectiveMillis}-${cooldown.globalValue??"builtin"}`} type="number" min="0" max="3600000" defaultValue={cooldown.effectiveMillis} onKeyDown={e=>{if(e.key==="Enter")setGlobalCooldown(cooldown,(e.target as HTMLInputElement).value)}}/><button className="secondary" onClick={e=>setGlobalCooldown(cooldown,e.currentTarget.parentElement?.querySelector("input")?.value??cooldown.effectiveMillis)}>Save ms</button><button className="secondary" disabled={!cooldown.overridden} onClick={()=>resetGlobalCooldown(cooldown)}>Use built-in</button></div></article>)}</div>
  </section>
  <section className="panel"><Title title="Latest blocked or failed actions" sub="Newest runtime problems across all agents."/>
   <div className="ledger-list">{problems.map((row:any)=><article className="ledger-card" key={row.id}>
    <div><strong>{row.display_name||row.character_name}</strong><small>{row.action_type} | {row.created_at}</small></div>
    <span className="inactive-state">{row.status}</span><p>{row.message}</p>
   </article>)}</div>{!problems.length&&<p className="muted">No blocked or failed actions recorded yet.</p>}</section>
  <section className="panel"><Title title="Session ledger" sub="Newest runtime sessions first."/>
   <div className="ledger-list">{sessions.map(session=><article className="ledger-card" key={session.id}>
    <div><strong>{session.display_name||session.character_name}</strong><small>{session.account_name} {"->"} {session.character_name}</small></div>
    <span className={Number(session.stale)===1||session.ended_at?"inactive-state":"active-state"}>{Number(session.stale)===1?"STALE":session.state}</span>
    <div className="ledger-grid"><Tile label="World" value={session.world}/><Tile label="Channel" value={session.channel}/><Tile label="Map" value={session.map_id}/><Tile label="Task" value={session.current_task||"none"}/><Tile label="Started" value={session.started_at}/><Tile label="Last tick" value={session.last_tick_at||"never"}/><Tile label="Ended" value={session.ended_at||"open"}/><Tile label="Stop reason" value={session.stop_reason||"none"}/></div>
    {Number(session.stale)===1&&!session.ended_at&&<div className="policy-actions"><button className="danger" onClick={()=>stopStaleSession(session)}>Mark stale stopped</button></div>}
   </article>)}</div>{!sessions.length&&<p className="muted">No runtime sessions recorded yet.</p>}</section></>
}

function Social(){
 const [q,setQ]=useState(""),[relationships,setRelationships]=useState<any[]>([]),[chat,setChat]=useState<any[]>([]),[proximity,setProximity]=useState<any[]>([]),[error,setError]=useState("");
 useEffect(()=>{const timer=setTimeout(()=>{api<any[]>(`/api/agents/social/relationships?q=${encodeURIComponent(q)}`).then(setRelationships).catch(x=>setError((x as Error).message));api<any[]>(`/api/agents/social/chat?q=${encodeURIComponent(q)}`).then(setChat).catch(x=>setError((x as Error).message));api<any[]>(`/api/agents/social/proximity?q=${encodeURIComponent(q)}`).then(setProximity).catch(x=>setError((x as Error).message))},160);return()=>clearTimeout(timer)},[q]);
 const companionNames=new Set(relationships.filter(row=>row.relationship_type==="COMPANION").map(row=>String(row.related_character_name||"").toLowerCase()));
 return <><article className="panel intro"><Title title="Social memory" sub="Companion targets, relationships and chat logs. FOLLOW_CHARACTER goals can seed companion relationships automatically."/></article>
  <PageToolbar query={q} onQueryChange={setQ} placeholder="Search agent, player, relationship, or message"/>
  {error&&<div className="error">{error}</div>}
  <section className="panel"><Title title="Nearby player observations" sub={`${proximity.length} recent perception snapshots. Companion targets are highlighted when visible.`}/>
   <div className="ledger-list">{proximity.map(row=>{const details=parseJson(row.details_json),players=details?.perception?.nearby?.players||[];return <article className="ledger-card social-card" key={row.id}>
    <div><strong>{row.display_name||row.agent_character_name}</strong><small>Map {details?.perception?.mapId??row.map_id??row.map} | {row.created_at}</small></div>
    {players.length?<div className="nearby-list">{players.map((player:any)=><span className={companionNames.has(String(player.name||"").toLowerCase())?"nearby-player companion":"nearby-player"} key={`${row.id}-${player.objectId}-${player.name}`}>
     <strong>{player.name||player.templateId||player.objectId}</strong><small>Lv. {player.level??"?"} | x {player.x??0}, y {player.y??0} | distanceSq {player.distanceSq??0}</small>
    </span>)}</div>:<p className="muted">No nearby players in this snapshot.</p>}
   </article>})}</div>{!proximity.length&&<p className="muted">No proximity snapshots yet. Enter an agent and run a runtime tick.</p>}</section>
  <div className="agent-detail"><section className="panel"><Title title="Relationships" sub={`${relationships.length} relationship records. COMPANION means the agent has been assigned or observed following that character.`}/>
   <div className="ledger-list">{relationships.map(row=><article className="ledger-card social-card" key={row.id}>
    <div><strong>{row.display_name||row.agent_character_name} {"->"} {row.related_character_name}</strong><small>{row.related_account_name} | {row.relationship_type}</small></div>
    <div className="ledger-grid"><Tile label="Trust" value={row.trust_score}/><Tile label="Affinity" value={row.affinity_score}/><Tile label="Updated" value={row.updated_at}/><Tile label="Notes" value={row.notes||"none"}/></div>
   </article>)}</div>{!relationships.length&&<p className="muted">No relationship records yet.</p>}</section>
   <section className="panel"><Title title="Chat logs" sub={`${chat.length} chat records.`}/>
   <div className="ledger-list">{chat.map(row=><article className="ledger-card social-card" key={row.id}>
    <div><strong>{row.display_name||row.agent_character_name}</strong><small>{row.channel_type} | {row.direction} | {row.created_at}</small></div>
    <p>{row.message}</p><small className="muted">Sender {row.sender_name||row.sender_character_id||"unknown"} | Recipient {row.recipient_name||row.recipient_character_id||"none"}</small>
   </article>)}</div>{!chat.length&&<p className="muted">No chat records yet.</p>}</section></div></>
}

function Economy(){
 const [q,setQ]=useState(""),[ledger,setLedger]=useState<any[]>([]),[error,setError]=useState("");
 useEffect(()=>{const timer=setTimeout(()=>{api<any[]>(`/api/agents/economy/ledger?q=${encodeURIComponent(q)}`).then(setLedger).catch(x=>setError((x as Error).message))},160);return()=>clearTimeout(timer)},[q]);
 const meso=ledger.reduce((sum,row)=>sum+Number(row.meso_delta||0),0);
 return <><article className="panel intro"><Title title="Economy ledger" sub="Item, meso, source and counterparty records for future trading, looting, merchant and reward behavior."/></article>
  <div className="metrics compact-metrics"><article><Coins/><small>Loaded entries</small><strong>{ledger.length}</strong></article><article><Coins/><small>Net meso delta</small><strong>{meso.toLocaleString()}</strong></article></div>
  <PageToolbar query={q} onQueryChange={setQ} placeholder="Search agent, item ID, entry type, source, or counterparty"/>
  {error&&<div className="error">{error}</div>}
  <section className="panel"><Title title="Ledger entries" sub="Newest economy records first."/>
   <div className="ledger-list">{ledger.map(row=><article className="ledger-card" key={row.id}>
    <div><strong>{row.display_name||row.agent_character_name}</strong><small>{row.entry_type} | {row.created_at}</small></div>
    <span className={Number(row.meso_delta||0)>=0?"active-state":"inactive-state"}>{Number(row.meso_delta||0).toLocaleString()} meso</span>
    <div className="ledger-grid"><Tile label="Item" value={row.item_id||"none"}/><Tile label="Quantity" value={row.quantity}/><Tile label="Source" value={`${row.source_type||"none"} ${row.source_id||""}`}/><Tile label="Counterparty" value={row.counterparty_name||row.counterparty_character_id||"none"}/><Tile label="World" value={row.world??"unset"}/><Tile label="Map" value={row.map_id??"unset"}/></div>
    {row.details_json&&<details><summary>Details JSON</summary><pre>{row.details_json}</pre></details>}
   </article>)}</div>{!ledger.length&&<p className="muted">No economy ledger entries yet.</p>}</section></>
}
